/**
 * PLACEHOLDER / STUB
 *
 * This file is GENERATED by the Convex CLI when you run:
 *   npx convex dev
 *   npx convex codegen
 *
 * Do not edit manually. The generated file exports typed API references for
 * all queries, mutations, and actions defined in convex/*.ts.
 *
 * Example generated shape:
 *   export const api = {
 *     todos: {
 *       list: FunctionReference<"query", "todos", "list">,
 *       add: FunctionReference<"mutation", "todos", "add">,
 *       toggle: FunctionReference<"mutation", "todos", "toggle">,
 *       remove: FunctionReference<"mutation", "todos", "remove">,
 *       greet: FunctionReference<"action", "todos", "greet">,
 *     },
 *   }
 *
 * Import and use: import { api } from "../convex/_generated/api"
 */

export const api = {
  todos: {
    list: {} as any,
    add: {} as any,
    toggle: {} as any,
    remove: {} as any,
    greet: {} as any,
  },
} as any

/**
 * PLACEHOLDER / STUB
 *
 * This file is GENERATED by the Convex CLI when you run:
 *   npx convex dev
 *   npx convex codegen
 *
 * Do not edit manually. The generated file exports typed API references for
 * all queries, mutations, and actions defined in convex/*.ts.
 *
 * Example generated shape:
 *   export const api = {
 *     todos: {
 *       list: FunctionReference<"query", "todos", "list">,
 *       add: FunctionReference<"mutation", "todos", "add">,
 *       toggle: FunctionReference<"mutation", "todos", "toggle">,
 *       remove: FunctionReference<"mutation", "todos", "remove">,
 *       greet: FunctionReference<"action", "todos", "greet">,
 *     },
 *   }
 *
 * Import and use: import { api } from "../convex/_generated/api"
 */

export const api = {
  todos: {
    list: {} as any,
    add: {} as any,
    toggle: {} as any,
    remove: {} as any,
    greet: {} as any,
  },
} as any
