/**
 * PLACEHOLDER / STUB
 *
 * This file is GENERATED by the Convex CLI when you run:
 *   npx convex dev
 *   npx convex codegen
 *
 * Do not edit manually. The generated file exports the query, mutation, and
 * action builders that wrap your Convex functions with type-safe context.
 *
 * Example generated shape:
 *   export { query, mutation, action } from "convex/server"
 *   // plus internal helpers for ctx.db, ctx.auth, etc.
 *
 * Import and use in convex/*.ts:
 *   import { mutation, query, action } from "./_generated/server"
 */

export { query, mutation, action } from "convex/server"

/**
 * PLACEHOLDER / STUB
 *
 * This file is GENERATED by the Convex CLI when you run:
 *   npx convex dev
 *   npx convex codegen
 *
 * Do not edit manually. The generated file exports the query, mutation, and
 * action builders that wrap your Convex functions with type-safe context.
 *
 * Example generated shape:
 *   export { query, mutation, action } from "convex/server"
 *   // plus internal helpers for ctx.db, ctx.auth, etc.
 *
 * Import and use in convex/*.ts:
 *   import { mutation, query, action } from "./_generated/server"
 */

export { query, mutation, action } from "convex/server"
