/**
 * Local-dev spec § 6 `generate-dev-stack.ts`: like generate-stack.ts but at
 * `.prisma-composer/dev/alchemy.run.ts`, always Alchemy stage `dev`, using
 * Alchemy's own `localState()` and no `report` — dev prints its own front
 * door (run-dev.ts), so core's presentation-free lower() gets nothing to
 * call back into.
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import type { AssembledServices } from '@internal/assemble';

export interface DevStackFileInput {
  /** Absolute path to the entry module (the app's default-exported node). */
  readonly entryPath: string;
  /** The process's cwd — where `.prisma-composer/dev/` is written. */
  readonly cwd: string;
  /** Absolute path to the discovered `prisma-composer.config.ts` — imported by relative path. */
  readonly configPath: string;
  readonly name: string;
  readonly assembled: AssembledServices;
}

const DEV_GENERATED_DIR = '.prisma-composer/dev';
const DEV_GENERATED_FILE = 'alchemy.run.ts';

/** A relative import specifier from `.prisma-composer/dev/alchemy.run.ts` to `target` (posix separators). */
function relativeImportSpecifier(generatedDir: string, target: string): string {
  const rel = path.relative(generatedDir, target).split(path.sep).join('/');
  return rel.startsWith('.') ? rel : `./${rel}`;
}

function quote(value: string): string {
  return JSON.stringify(value);
}

function renderBundle(bundle: { dir: string; entry: string }): string {
  return `{ dir: ${quote(bundle.dir)}, entry: ${quote(bundle.entry)} }`;
}

function renderOptions(input: DevStackFileInput): string {
  const lines: string[] = [];
  lines.push(`  name: ${quote(input.name)},`);

  lines.push('  bundles: {');
  for (const [id, bundle] of Object.entries(input.assembled.bundles)) {
    lines.push(`    ${quote(id)}: ${renderBundle(bundle)},`);
  }
  lines.push('  },');

  lines.push('  dev: true,');
  lines.push('  state: localState(),');

  return lines.join('\n');
}

/** Renders the dev stack module's source (tests assert on it without touching disk). */
export function renderDevStackFile(input: DevStackFileInput): string {
  const generatedDir = path.join(input.cwd, DEV_GENERATED_DIR);
  const appImport = relativeImportSpecifier(generatedDir, input.entryPath);
  const configImport = relativeImportSpecifier(generatedDir, input.configPath);

  return `// Generated by \`prisma-composer dev\` — overwritten on every run; do not
// edit by hand. Independently runnable from ${quote(input.cwd)}:
//
//   alchemy deploy ${DEV_GENERATED_DIR}/${DEV_GENERATED_FILE} --stage dev
//
// bisects a CLI bug from an Alchemy bug (deploy-cli.md § Implementation decisions).
import { lower } from '@prisma/composer/deploy';
import { localState } from 'alchemy/State/LocalState';
import config from ${quote(configImport)};
import app from ${quote(appImport)};

export default lower(app, config, {
${renderOptions(input)}
});
`;
}

/** Writes the dev stack file, returning its absolute path. */
export function writeDevStackFile(input: DevStackFileInput): string {
  const generatedDir = path.join(input.cwd, DEV_GENERATED_DIR);
  fs.mkdirSync(generatedDir, { recursive: true });
  const filePath = path.join(generatedDir, DEV_GENERATED_FILE);
  fs.writeFileSync(filePath, renderDevStackFile(input));
  return filePath;
}

export const DEV_STACK_RELATIVE_PATH = path.join(DEV_GENERATED_DIR, DEV_GENERATED_FILE);
