// The app's own entrypoint (the build adapter's `entry`). The pack-printed
// bootstrap imports this AFTER run(address, boot) has re-keyed the platform
// environment address-free, so service.load() reads it directly.
//
// A genuine round trip through the contract's schema: each request inserts a
// Widget (its id auto-generated by the contract's uuid default) and reads the
// rows back through the SAME typed Prisma Next client, returning the newest
// label + the row count. The e2e verify script asserts the label round-trips.

import service from './service.ts';

const { db } = service.load(); // db: { url, client } — the Prisma Next binding (ADR-0040)
const port = service.port();

// A Prisma Postgres direct connection is dropped when it idles / the service
// scales to zero; the lazy pool reconnects on the next query. Surface those as
// logs, not an uncaught crash into a 502 restart loop.
process.on('uncaughtException', (err) => console.error('uncaughtException', err));
process.on('unhandledRejection', (err) => console.error('unhandledRejection', err));

const handler = async (): Promise<Response> => {
  try {
    const label = `widget-${Date.now()}`;
    const created = await db.client.orm.public.Widget.create({ label });
    const all = await db.client.orm.public.Widget.all();
    return Response.json({ ok: true, label: created.label, count: all.length });
  } catch (err) {
    console.error('widget round trip failed', err);
    return Response.json({ ok: false }, { status: 503 });
  }
};

// Bind all interfaces — Compute routes external HTTP to the VM, so a
// loopback-only listener would be unreachable.
Bun.serve({ port, hostname: '0.0.0.0', fetch: handler });
