/**
 * Pipeline step 6 (deploy-cli.md § The pipeline; design-notes.md's "Driving
 * Alchemy" call): writes a small, human-readable, regenerated-every-run stack
 * module at `.prisma-app/alchemy.run.ts` inside the process's own working
 * directory — tool state lives where you run the tool, like every other CLI
 * (ADR-0004's rewrite; no package-anchor walk). It calls `lower()` with the
 * values the CLI already computed — no logic of its own, so it stays
 * independently runnable (`alchemy deploy .prisma-app/alchemy.run.ts`) to
 * bisect a CLI bug from an Alchemy bug.
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import type { AssembledServices } from '@prisma/app-assemble';

export interface StackFileInput {
  /** Absolute path to the entry module (the app's default-exported node). */
  readonly entryPath: string;
  /** The process's cwd — where `.prisma-app/` is written. */
  readonly cwd: string;
  /** The pack package name whose `/target` supplies `fromEnv()`. */
  readonly pack: string;
  readonly name: string;
  // No `stage` field: core's lower() never reads LowerOptions.stage — the
  // effective stage is Alchemy's own, passed as `--stage` on the alchemy
  // invocation (run-alchemy.ts).
  readonly assembled: AssembledServices;
}

const GENERATED_DIR = '.prisma-app';
const GENERATED_FILE = 'alchemy.run.ts';

/** A relative import specifier from `.prisma-app/alchemy.run.ts` to `target`. */
function relativeImportSpecifier(generatedDir: string, target: string): string {
  const rel = path.relative(generatedDir, target).split(path.sep).join('/');
  return rel.startsWith('.') ? rel : `./${rel}`;
}

function quote(value: string): string {
  return JSON.stringify(value);
}

function renderBundle(bundle: { dir: string; entry: string }): string {
  return `{ dir: ${quote(bundle.dir)}, entry: ${quote(bundle.entry)} }`;
}

function renderOptions(input: StackFileInput): string {
  const lines: string[] = [];
  lines.push(`  name: ${quote(input.name)},`);

  lines.push('  bundles: {');
  for (const [id, bundle] of Object.entries(input.assembled.bundles)) {
    lines.push(`    ${quote(id)}: ${renderBundle(bundle)},`);
  }
  lines.push('  },');

  return lines.join('\n');
}

/**
 * Renders the stack module's source — exported separately so tests can
 * assert on its content without touching disk.
 *
 * The header is `//` line comments, not a block comment (F01): a `cwd`
 * containing a star immediately followed by a slash — a legal (if exotic)
 * unix path, e.g. a directory named "foo*" — would close a block comment
 * early and emit a syntactically broken stack file. `//` has no closing
 * delimiter for a path to collide with.
 */
export function renderStackFile(input: StackFileInput): string {
  const generatedDir = path.join(input.cwd, GENERATED_DIR);
  const appImport = relativeImportSpecifier(generatedDir, input.entryPath);

  return `// Generated by \`prisma-app deploy\`/\`prisma-app destroy\` — overwritten on every
// run; do not edit by hand. Independently runnable from ${quote(input.cwd)}:
//
//   alchemy deploy ${GENERATED_DIR}/${GENERATED_FILE}
//
// bisects a CLI bug from an Alchemy bug (deploy-cli.md § Implementation decisions).
import { lower } from '@prisma/app/deploy';
import { fromEnv } from ${quote(`${input.pack}/target`)};
import app from ${quote(appImport)};

export default lower(app, fromEnv(), {
${renderOptions(input)}
});
`;
}

/** Writes the stack file, returning its absolute path. */
export function writeStackFile(input: StackFileInput): string {
  const generatedDir = path.join(input.cwd, GENERATED_DIR);
  fs.mkdirSync(generatedDir, { recursive: true });
  const filePath = path.join(generatedDir, GENERATED_FILE);
  fs.writeFileSync(filePath, renderStackFile(input));
  return filePath;
}

export const GENERATED_STACK_RELATIVE_PATH = path.join(GENERATED_DIR, GENERATED_FILE);
