/** Pipeline step 6: writes a regenerated-every-run, independently runnable stack module at `.prisma-compose/alchemy.run.ts`. */
import * as fs from 'node:fs';
import * as path from 'node:path';
import type { AssembledServices } from '@prisma/compose-assemble';

export interface StackFileInput {
  /** Absolute path to the entry module (the app's default-exported node). */
  readonly entryPath: string;
  /** The process's cwd — where `.prisma-compose/` is written. */
  readonly cwd: string;
  /** Absolute path to the discovered `prisma-compose.config.ts` — imported by relative path. */
  readonly configPath: string;
  readonly name: string;
  // No `stage` field: core's lower() never reads LowerOptions.stage — the
  // effective stage is Alchemy's own, passed as `--stage` on the alchemy
  // invocation (run-alchemy.ts).
  readonly assembled: AssembledServices;
}

const GENERATED_DIR = '.prisma-compose';
const GENERATED_FILE = 'alchemy.run.ts';

/** A relative import specifier from `.prisma-compose/alchemy.run.ts` to `target` (posix separators). */
function relativeImportSpecifier(generatedDir: string, target: string): string {
  const rel = path.relative(generatedDir, target).split(path.sep).join('/');
  return rel.startsWith('.') ? rel : `./${rel}`;
}

function quote(value: string): string {
  return JSON.stringify(value);
}

function renderBundle(bundle: { dir: string; entry: string }): string {
  return `{ dir: ${quote(bundle.dir)}, entry: ${quote(bundle.entry)} }`;
}

function renderOptions(input: StackFileInput): string {
  const lines: string[] = [];
  lines.push(`  name: ${quote(input.name)},`);

  lines.push('  bundles: {');
  for (const [id, bundle] of Object.entries(input.assembled.bundles)) {
    lines.push(`    ${quote(id)}: ${renderBundle(bundle)},`);
  }
  lines.push('  },');

  return lines.join('\n');
}

/** Renders the stack module's source (tests assert on it without touching disk) — uses `//` headers, not a block comment, since a cwd path with a star-slash could close one early. */
export function renderStackFile(input: StackFileInput): string {
  const generatedDir = path.join(input.cwd, GENERATED_DIR);
  const appImport = relativeImportSpecifier(generatedDir, input.entryPath);
  const configImport = relativeImportSpecifier(generatedDir, input.configPath);

  return `// Generated by \`prisma-compose deploy\`/\`prisma-compose destroy\` — overwritten on every
// run; do not edit by hand. Independently runnable from ${quote(input.cwd)}:
//
//   alchemy deploy ${GENERATED_DIR}/${GENERATED_FILE}
//
// bisects a CLI bug from an Alchemy bug (deploy-cli.md § Implementation decisions).
import { lower } from '@prisma/compose/deploy';
import config from ${quote(configImport)};
import app from ${quote(appImport)};

export default lower(app, config, {
${renderOptions(input)}
});
`;
}

/** Writes the stack file, returning its absolute path. */
export function writeStackFile(input: StackFileInput): string {
  const generatedDir = path.join(input.cwd, GENERATED_DIR);
  fs.mkdirSync(generatedDir, { recursive: true });
  const filePath = path.join(generatedDir, GENERATED_FILE);
  fs.writeFileSync(filePath, renderStackFile(input));
  return filePath;
}

export const GENERATED_STACK_RELATIVE_PATH = path.join(GENERATED_DIR, GENERATED_FILE);
