// Generated by `prisma-compose deploy`/`prisma-compose destroy` — overwritten on every
// run; do not edit by hand. Independently runnable from "/Users/will/Projects/prisma/compose/.claude/worktrees/prisma-compose-demo-app-07178e/examples/store":
//
//   alchemy deploy .prisma-compose/alchemy.run.ts
//
// bisects a CLI bug from an Alchemy bug (deploy-cli.md § Implementation decisions).
import { lower } from '@prisma/compose/deploy';
import app from '../module.ts';
import config from '../prisma-compose.config.ts';

export default lower(app, config, {
  name: 'store',
  bundles: {
    'catalog.service': {
      dir: '/Users/will/Projects/prisma/compose/.claude/worktrees/prisma-compose-demo-app-07178e/examples/store/modules/catalog/dist/bundle',
      entry: 'server.mjs',
    },
    'orders.service': {
      dir: '/Users/will/Projects/prisma/compose/.claude/worktrees/prisma-compose-demo-app-07178e/examples/store/modules/orders/dist/bundle',
      entry: 'server.mjs',
    },
    storefront: {
      dir: '/Users/will/Projects/prisma/compose/.claude/worktrees/prisma-compose-demo-app-07178e/examples/store/modules/storefront/.next/standalone/examples/store/modules/storefront',
      entry: 'server.js',
    },
  },
});
